### ISSUE TITLE
Error when inventory full

### ISSUE THREAD

**Issue by Choumiko** [Cheata/bulldozer#2]
Once the inventory of the bulldozer has a full inventory (meaning all slots occupied) and it tries to pickup an item-on-ground i get this (line 214 in your release)
![wmpsnpj](https://cloud.githubusercontent.com/assets/5612780/6893724/87d87d36-d6cf-11e4-8bd6-ac5667355fc9.png)

**Comment by Cheata** [comment]
this error only occurs with your fixes applied. specifically the blacklist as a table, Its due to the fact that "item-on-ground" is a "name" not a "type" same thing may occur with the stone rock ... ill attend to it now

**Comment by Cheata** [comment]
fixed
